function [fitresult, gof] = createFit_NofE(E, nn)
%CREATEFIT(E,NN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : E
%      Y Output: nn
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2020 15:02:41


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( E, nn );

% Set up fittype and options.
ft = fittype( 'c1*x+c2*x^0.5+c0', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.599520982350974 0.383897233759887 0.433488524191775];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'nn vs. E', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'E', 'Interpreter', 'none' );
ylabel( 'nn', 'Interpreter', 'none' );
grid on


